version: "3"
services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./log/:/var/log/
      - ./learn:/learn
      - ../web:/code
    links:
      - php
    ports:
      - "80:80"
      - "443:443"
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./php/:/usr/local/etc/php/php.ini
      - ../web:/code
      - ./learn:/learn
      - ./log/:/var/log/
    links:
      - mysql
    ports:
      - "9000:9000"
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./log/:/var/log/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
